[package]
name = "legible_font_upscale"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = "0.8.2"
candle-nn = "0.8.2"
embed_anything = "0.5.1"
image = "0.23.14"
tokio = { version = "1.16.1", features = ["full"] }
